### ISSUE TITLE
Module update

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xsitemap#10]
JJDai did an update of this module:
https://www.frxoops.org/modules/newbb/viewtopic.php?topic_id=38138

**Comment by mambax7** [comment]
That's great! 
He should submit it a Pull Request here.

**Comment by mambax7** [comment]
Did you ask him to submit a PR here?

**Comment by cesagonchu** [comment]
Yes, but he said Github is too complicated for his age :)

**Comment by GregMage** [comment]
Too bad. So we can close it!
