### ISSUE TITLE
Failed to open stream error

### ISSUE THREAD

**Issue by geeronzero** [XoopsModules25x/xsitemap#13]
Предупреждение: require_once(/modules/xsitemap/class/plugin.php): failed to open stream: ��� ������ ����� ��� �������� в файле /modules/xsitemap/admin/xml.php строка 37

This error is caused by capital letter in php files naming. The simplest solution is change the "require once" statement within /modules/xsitemap/admin/xml.php at string 37:

require_once $GLOBALS['xoops']->path('modules/' . $moduleDirName . '/class/Plugin.php');

**Comment by mambax7** [comment]
Thanks! It should be fixed now in https://github.com/XoopsModules25x/xsitemap/releases/tag/1.55_BETA_1
Please re-open, if there is still an issue.
