### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by AxelF1977** [XoopsModules25x/xsitemap#15]
Hey, 

just to let you know, I get this error when I want to view the xml file

![image](https://user-images.githubusercontent.com/45079419/104482360-230f7300-55c7-11eb-9c74-4156b483753a.png)

**Comment by mambax7** [comment]
Thanks! It should be now fixed in: https://github.com/XoopsModules25x/xsitemap/releases/tag/1.55_BETA_2
