### ISSUE TITLE
XML FIle with HTML entity 

### ISSUE THREAD

**Issue by AxelF1977** [XoopsModules25x/xsitemap#17]
Instead of https:// its https&colon;&sol;&sol; in the xml file.

**Comment by mambax7** [comment]
These are equal:

https:// and  https://

so I'm not sure, I understand...

**Comment by AxelF1977** [comment]
That´s how it´s look in xml file

![image](https://user-images.githubusercontent.com/45079419/104563025-70342900-5649-11eb-8793-d4871689d3ca.png)

In the old version it was clear written https://

**Comment by mambax7** [comment]
It's just coding: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

**Comment by AxelF1977** [comment]
I know what it is :-) 

google says to it: In addition, all URLs (including the URL of your sitemap) must be encoded for readability by the web server on which they are located and URL-escaped. 

In my sitemap the urls are not encoded now. Or do I get it wrong Mamba?

**Comment by mambax7** [comment]
OK, try this one version: https://github.com/XoopsModules25x/xsitemap/releases/tag/1.55_BETA_3

**Comment by AxelF1977** [comment]
Perfect, it´s gone. The sitemap is now encoded. 
Thank you Mamba

**Comment by mambax7** [comment]
Thanks for testing!
